version: "3"
services:

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ../mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456
  # Web
  nginx:
    build: ./nginx
    links:
      - php7
    volumes:
      - ../api.invest:/var/www/api.invest
      - ../frontend.invest:/var/www/frontend.invest
      - ../rangdong:/var/www/rangdong
      # Logs
      - ./nginx/log:/var/log/nginx
    ports:
      - "85:85"
      - "86:86"
      - "87:87"
    networks:
      - all

  # PHP
  php7:
    build: ./php
    container_name: php7
    volumes:
      - ../api.invest:/var/www/api.invest
      - ../frontend.invest:/var/www/frontend.invest
      - ../rangdong:/var/www/rangdong
      # Logs
      - ./php/log:/var/log/php
    networks:
      - all

networks:
  all:
    driver: bridge
