version: "3"
services:

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ../mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456
  # Web
  nginx:
    build: ./nginx
    links:
      - php7
    volumes:
      - ../api_invest:/var/www/api_invest
      - ../frontend_invest:/var/www/frontend_invest
      - ../api-web-invest:/var/www/api-web-invest
      - ../website_invest:/var/www/website_invest
      - ../upload_service:/var/www/upload_service
      # Logs
      - ./nginx/log:/var/log/nginx
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
    networks:
      - all

  # PHP
  php7:
    build: ./php
    container_name: php7
    volumes:
      - ../api_invest:/var/www/api_invest
      - ../frontend_invest:/var/www/frontend_invest
      - ../api-web-invest:/var/www/api-web-invest
      - ../website_invest:/var/www/website_invest
      - ../upload_service:/var/www/upload_service
      # Logs
      - ./php/log:/var/log/php
    networks:
      - all

networks:
  all:
    driver: bridge
