version: "3"
services:

  db:
    image: mysql:5.7
    ports:
      - "3366:3306"
    volumes:
      - ../mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - '8080:80'
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: 123456
  # Web
  nginx:
    build: ./nginx
    links:
      - php7-wsl
      - php8-wsl
    volumes:
      - ../xnt-wsl:/var/www/xnt-wsl
      - ../apos:/var/www/apos
      # Logs
      - ./nginx/log:/var/log/nginx
    ports:
      - "8005:8005"
      - "8004:8004"
    networks:
      - all

  # PHP7
  php7-wsl:
    build: ./php
    container_name: php7-wsl
    volumes:
      - ../apos:/var/www/apos
      # Logs
      - ./php/log:/var/log/php
    networks:
      - all

  # PHP8
  php8-wsl:
    build: ./php8
    container_name: php8-wsl
    volumes:
      - ../xnt-wsl:/var/www/xnt-wsl
      # Logs
      - ./php8/log:/var/log/php8
    networks:
      - all

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - all
  
  queue:
    build: ./supervisor
    depends_on:
      - php8-wsl
      - redis
    volumes:
      - ../xnt-wsl:/var/www/xnt-wsl
      # Logs
    environment:
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_CONNECTION=mysql
      - DB_HOST=host.docker.internal
      - DB_PORT=3366
      - DB_DATABASE=aladdin_xnt
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    networks:
      - all

networks:
  all:
    driver: bridge
